### ISSUE TITLE
uncaught exception: out of bounds access

### ISSUE THREAD

**Issue by Raynos** [uber/hyperbahn#217]
```
RangeError: Trying to access beyond buffer length
    at checkOffset (buffer.js:582:11)
    at Buffer.readUInt16BE (buffer.js:602:5)
    at BufferRW.readLazyFrameFrom [as readFrom] (/var/cache/udeploy/r/hyperbahn/sjc1-produ-0000000111-v1/node_modules/hyperbahn/node_modules/tchannel/v2/lazy_frame.js:90:23)
    at fromBufferResult (/var/cache/udeploy/r/hyperbahn/sjc1-produ-0000000111-v1/node_modules/hyperbahn/node_modules/bufrw/interface.js:120:18)
    at ReadMachine.seek (/var/cache/udeploy/r/hyperbahn/sjc1-produ-0000000111-v1/node_modules/hyperbahn/node_modules/bufrw/stream/read_machine.js:116:15)
    at ReadMachine.handleChunk (/var/cache/udeploy/r/hyperbahn/sjc1-produ-0000000111-v1/node_modules/hyperbahn/node_modules/bufrw/stream/read_machine.js:67:28)
    at Socket.onSocketChunk (/var/cache/udeploy/r/hyperbahn/sjc1-produ-0000000111-v1/node_modules/hyperbahn/node_modules/tchannel/connection.js:451:29)
    at Socket.emit (events.js:95:17)
    at SocketInspector.inspectEmit (/var/cache/udeploy/r/hyperbahn/sjc1-produ-0000000111-v1/node_modules/hyperbahn/clients/socket-inspector.js:132:23)
    at Socket.boundInspectEmit [as emit] (/var/cache/udeploy/r/hyperbahn/sjc1-produ-0000000111-v1/node_modules/hyperbahn/clients/socket-inspector.js:51:14)
    at Socket.<anonymous> (_stream_readable.js:764:14)
    at Socket.emit (events.js:92:17)
    at SocketInspector.inspectEmit (/var/cache/udeploy/r/hyperbahn/sjc1-produ-0000000111-v1/node_modules/hyperbahn/clients/socket-inspector.js:132:23)
    at Socket.boundInspectEmit [as emit] (/var/cache/udeploy/r/hyperbahn/sjc1-produ-0000000111-v1/node_modules/hyperbahn/clients/socket-inspector.js:51:14)
    at emitReadable_ (_stream_readable.js:426:10)
    at emitReadable (_stream_readable.js:422:5)
    at readableAddChunk (_stream_readable.js:165:9)
    at Socket.Readable.push (_stream_readable.js:127:10)
    at TCP.onread (net.js:528:21)
```

**Comment by kriskowal** [comment]
3 more of these at 2016-01-27 10:40. Probably induced by probing during development.
